#!/bin/bash

if [[ -z "$1" ]]; then
    echo usage: $0 \<backup_name\>
    exit 1
fi

save_path="$(pwd)/$1"

if [[ ! -d "$save_path" ]]; then
    echo file path "$save_path" does not exist, aborted.
    exit 1
fi

echo loading from path $save_path, are you sure?

read i

if [[ ! "$i" == "y" ]]; then
    echo aborted.
    exit 1
fi

# else

# copy all of these
# /14/ /world
# /15/󰗀 /mod_config.xml
# /16/ /mod_settings.bin
# /17/󰗀 /player.xml
# /18/ /session_numbers.salakieli
# /20/󰗀 /world_state.xml

auto_backup_path="$(pwd)/save00.autobak"

if [[ -d "$auto_backup_path" ]]; then
    echo backup path exists $auto_backup_path, removing...
    rm -r "$auto_backup_path"
fi

echo proceeding to move, for backup ./save00/{mod_config.xml,world,mod_settings.bin,player.xml,session_numbers.salakieli,world_state.xml} to "$auto_backup_path"

mkdir -p "$auto_backup_path"
mv ./save00/{mod_config.xml,world,mod_settings.bin,player.xml,session_numbers.salakieli,world_state.xml} "$auto_backup_path"

echo done backup

echo loading save...
cp -r "$save_path"/* ./save00
echo done

